version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlpreview
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mana@123
      - MSSQL_PID=Evaluation
    ports:
      - "1434:1433"
    networks:
      - my_network
    volumes:
      - ./sql-scripts:/var/opt/mssql/scripts
    command: /opt/mssql/bin/sqlservr

  productmanagementapi:
    build:
      context: ./SWP.ProductManagement.API
      dockerfile: Dockerfile
    container_name: productmanagementapi
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlpreview;Database=ProductManagement;User Id=sa;Password=Mana@123;TrustServerCertificate=True;
    ports:
      - "8888:8080"
    networks:
      - my_network

  demo-react:
    build:
      context: ./demo-react
      dockerfile: Dockerfile
    container_name: demo-react
    environment:
      - VITE_API_URL=http://128.199.177.223:8888
    ports:
      - "3000:80"
    networks:
      - my_network
    
networks:
  my_network:
    driver: bridge
